import { MenuItem, Testimonial } from '@/types';

export const menuItems: MenuItem[] = [
  {
    id: '1',
    name: 'Chicken Shawarma',
    description: 'Juicy chicken wrapped in warm pita bread with garlic sauce',
    price: 180,
    image: 'https://images.unsplash.com/photo-1606756790138-261d2b21cd75?w=600&q=80',
    category: 'Shawarma',
    rating: 4.8,
    available: true,
  },
  {
    id: '2',
    name: 'Beef Burger',
    description: 'Premium beef patty with lettuce, tomato, and special sauce',
    price: 250,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80',
    category: 'Burgers',
    rating: 4.6,
    available: true,
  },
  {
    id: '3',
    name: 'French Fries',
    description: 'Crispy golden fries seasoned with herbs',
    price: 120,
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=600&q=80',
    category: 'Fries',
    rating: 4.5,
    available: true,
  },
  {
    id: '4',
    name: 'Chicken Burger',
    description: 'Crispy chicken fillet with coleslaw and mayo',
    price: 200,
    image: 'https://images.unsplash.com/photo-1565299507177-b0ac6056380b?w=600&q=80',
    category: 'Burgers',
    rating: 4.4,
    available: true,
  },
  {
    id: '5',
    name: 'Lemon Mint',
    description: 'Refreshing lemon mint cooler',
    price: 80,
    image: 'https://images.unsplash.com/photo-1621263764928-df1444c5e859?w=600&q=80',
    category: 'Drinks',
    rating: 4.3,
    available: true,
  },
  {
    id: '6',
    name: 'Grilled Sandwich',
    description: 'Toasted sandwich with veggies and cheese',
    price: 150,
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=600&q=80',
    category: 'Burgers',
    rating: 4.2,
    available: true,
  },
  {
    id: '7',
    name: 'Chocolate Milkshake',
    description: 'Rich and creamy chocolate milkshake',
    price: 140,
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=600&q=80',
    category: 'Drinks',
    rating: 4.7,
    available: true,
  },
  {
    id: '8',
    name: 'Veg Shawarma',
    description: 'Fresh vegetables with hummus in pita bread',
    price: 150,
    image: 'https://images.unsplash.com/photo-1656995235801-0c01b1e68c9b?w=600&q=80',
    category: 'Shawarma',
    rating: 4.1,
    available: true,
  },
  {
    id: '9',
    name: 'Chicken Combo',
    description: 'Chicken shawarma + fries + drink',
    price: 350,
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&q=80',
    category: 'Combos',
    rating: 4.9,
    available: true,
  },
  {
    id: '10',
    name: 'Mango Shake',
    description: 'Fresh mango milkshake with cream',
    price: 130,
    image: 'https://images.unsplash.com/photo-1527661591475-527312dd65f5?w=600&q=80',
    category: 'Drinks',
    rating: 4.5,
    available: true,
  },
  {
    id: '11',
    name: 'Chicken Nuggets',
    description: 'Crispy chicken nuggets with dip',
    price: 160,
    image: 'https://images.unsplash.com/photo-1562967914-608f82629710?w=600&q=80',
    category: 'Fries',
    rating: 4.3,
    available: true,
  },
  {
    id: '12',
    name: 'Brownie Sundae',
    description: 'Warm chocolate brownie with ice cream',
    price: 200,
    image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=600&q=80',
    category: 'Desserts',
    rating: 4.8,
    available: true,
  },
];

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Priya Sharma',
    review: 'The queue skipping feature is a game changer! Ordered my shawarma and picked it up without waiting.',
    rating: 5,
  },
  {
    id: '2',
    name: 'Rahul Kumar',
    review: 'Best burger in Chennai. The online ordering is super smooth and the food is always fresh.',
    rating: 5,
  },
  {
    id: '3',
    name: 'Ananya Patel',
    review: 'I love scheduling my pickup during lunch break. Saves so much time!',
    rating: 4,
  },
  {
    id: '4',
    name: 'Vikram Singh',
    review: 'The combos are amazing value. Great food, great service, no queues.',
    rating: 5,
  },
  {
    id: '5',
    name: 'Divya Rajan',
    review: 'Finally a food place that respects my time. The tracking feature is brilliant.',
    rating: 5,
  },
];

export const categories = [
  'All',
  'Burgers',
  'Shawarma',
  'Fries',
  'Drinks',
  'Combos',
  'Desserts',
];
